"use strict";

(() => {
  const content = document.querySelector("#content");
  const toast = document.querySelector("#toast");
  const dialog = document.querySelector("#dialog");
  const dialogContent = document.querySelector("#dialog-content");
  const navNames = { overview: "账号概览", binding: "绑定账号", history: "运行记录" };
  const initial = {
    view: location.hash.slice(1) || "overview",
    share: true,
    push: "none",
    pushTestSent: false,
    bindingStep: 0,
    claimed: 37,
    batchClaimed: 7,
    activeFilter: "全部",
  };
  const state = { ...initial };
  const runs = [
    { date: "09/21 08:19", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已完成", rewards: ["积分 774 → 780", "能量体 +2", "签到卡 +1"] },
    { date: "09/20 08:16", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已跳过", rewards: ["积分 768 → 774"] },
    { date: "09/19 08:11", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已完成", rewards: ["积分 762 → 768", "能量体 +2"] },
    { date: "09/18 08:34", task: "每日任务", result: "部分完成", tone: "warn", sign: "已签到", share: "未完成", rewards: ["积分 756 → 762", "分享接口稍后重试"] },
    { date: "09/17 08:22", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已完成", rewards: ["积分 750 → 756", "签到卡 +1"] },
    { date: "09/16 08:27", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已完成", rewards: ["积分 744 → 750", "能量体 +2"] },
    { date: "09/15 08:09", task: "每日任务", result: "已完成", tone: "success", sign: "已签到", share: "已完成", rewards: ["积分 738 → 744"] },
  ];

  const icon = (name) => `<i data-lucide="${name}"></i>`;
  const html = (value) => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
  const button = (label, action, classes = "") => `<button class="${classes}" data-action="${action}">${label}</button>`;
  function notify(message) {
    toast.innerHTML = `${icon("check-circle-2")}<span>${html(message)}</span>`;
    toast.hidden = false;
    window.clearTimeout(notify.timer);
    notify.timer = window.setTimeout(() => { toast.hidden = true; }, 2400);
    window.lucide?.createIcons();
  }
  function badge(label, tone = "") { return `<span class="badge ${tone}"><i></i>${html(label)}</span>`; }
  function rewardList(items) { return `<div class="reward-list">${items.map((item) => `<span class="reward ${item.includes("能量") ? "energy" : item.includes("签到卡") ? "card" : item.includes("重试") ? "error" : ""}">${html(item)}</span>`).join("")}</div>`; }
  function renderOverviewLegacy() {
    content.innerHTML = `
      <section class="account-strip"><div class="avatar">山</div><div><div class="account-name">山海之间</div><div class="account-meta"><span>账号用户</span><span>每日 08:00 - 10:00</span><span>连续签到 16 天</span></div></div><div class="account-strip-actions"><div class="badge success"><i></i>任务运行中</div><button class="binding-settings" data-action="binding-settings">${icon("settings-2")}绑定设置</button></div></section>
      <section class="metrics"><div class="metric"><div class="metric-label">${icon("calendar-check-2")}今日签到</div><div class="metric-number">已完成</div><div class="metric-foot"><b>08:19</b> · 本地时间</div></div><div class="metric"><div class="metric-label">${icon("star")}当前积分</div><div class="metric-number">780 <small>分</small></div><div class="metric-foot"><b>+6</b> · 今日奖励</div></div><div class="metric"><div class="metric-label">${icon("ticket")}签到卡</div><div class="metric-number">12 <small>张</small></div><div class="metric-foot">最近查询 08:20</div></div><div class="metric"><div class="metric-label">${icon("flame")}连续签到</div><div class="metric-number">16 <small>天</small></div><div class="metric-foot">本月已签到 16 天</div></div></section>
      <div class="two-columns"><section class="section today-section"><div class="section-header"><div><h2>今日任务</h2><p class="eyebrow">2026 年 09 月 21 日</p></div>${badge("已完成", "success")}</div><div class="task-line"><div class="task-symbol">${icon("calendar-check-2")}</div><div><strong>每日签到</strong><small>今日已完成，重复触发会自动跳过</small></div><span class="task-reward">+6 积分</span>${icon("check")}</div><div class="task-line"><div class="task-symbol energy">${icon("share-2")}</div><div><strong>每日分享</strong><small>签到时同时完成分享</small></div><span class="task-reward energy-text">+2 能量体</span>${icon("check")}</div><div class="action-row">${button(`${icon("play")}立即签到一次`, "run", "primary")}${button(`${icon("pause")}暂停任务`, "pause")}</div><div class="next-run">${icon("clock-3")}下一次执行：明天 08:00 - 10:00 内随机执行</div></section><section class="section"><div class="section-header"><div><h2>任务设置</h2><p class="eyebrow">保存后从下一次任务开始生效</p></div>${badge("名额充足", "blue")}</div><form class="schedule-form" data-form="schedule"><label class="field"><span class="field-heading">每日执行区间（北京时间）<span>每两小时随机执行</span></span><select name="window"><option>08:00 - 10:00</option><option>10:00 - 12:00</option><option>12:00 - 14:00</option><option>18:00 - 20:00</option></select></label><div class="availability">本区间剩余 9 / 10 个名额 <span class="availability-bar"><b style="width:90%"></b></span></div><label class="switch-line"><span>签到时同时完成分享</span><input name="share" type="checkbox" ${state.share ? "checked" : ""}></label><div class="form-footer"><span>暂停账号仍占用执行名额</span><button class="primary" type="submit">${icon("save")}保存设置</button></div></form></section></div>
      <section class="push-section"><div><h2>结果推送</h2><p>每次任务完成后发送一次结果通知</p></div><div><div class="push-options"><label>${icon("bell-off")}<input type="radio" name="preview-push" value="none" ${state.push === "none" ? "checked" : ""}>不推送</label><label>${icon("smartphone")}<input type="radio" name="preview-push" value="bark" ${state.push === "bark" ? "checked" : ""}>Bark</label><label>${icon("message-square-text")}<input type="radio" name="preview-push" value="serverchan" ${state.push === "serverchan" ? "checked" : ""}>Server 酱</label></div><div id="push-field" class="push-field" ${state.push === "none" ? "hidden" : ""}><input type="password" placeholder="${state.push === "bark" ? "输入 Bark Device Key" : "输入 Server 酱 SendKey"}"><button data-action="save-push" class="primary">保存并发送测试消息</button></div>${state.pushTestSent ? `<p class="push-test-status">${icon("check-circle-2")}测试消息已发送 · 刚刚</p>` : ""}</div></section>
      <section class="danger-zone"><div><h2>账号管理</h2><p>解除绑定会停止每日任务，并删除云端保存的登录状态。</p></div><button class="danger" data-action="unbind">${icon("unlink")}解除绑定</button></section>
      <section class="section"><div class="section-header"><div><h2>最近运行</h2><p class="eyebrow">展示最近 7 次云端任务结果</p></div><a class="text-button" href="#history" data-nav="history">查看全部 ${icon("arrow-right")}</a></div><div class="table-wrap"><table><thead><tr><th>执行时间</th><th>任务</th><th>结果</th><th>签到 / 分享</th><th>奖励</th></tr></thead><tbody>${runs.slice(0, 4).map((run) => `<tr><td><strong>${run.date}</strong><small>北京时间</small></td><td>${run.task}</td><td>${badge(run.result, run.tone)}</td><td>${run.sign} / ${run.share}</td><td>${rewardList(run.rewards)}</td></tr>`).join("")}</tbody></table></div></section>`;
  }
  function renderOverview() {
    content.innerHTML = `
      <section class="account-strip"><div class="avatar">山</div><div><div class="account-name">山海之间</div><div class="account-meta"><span>账号用户</span><span>每日 08:00 - 10:00</span><span>连续签到 16 天</span></div></div><div class="account-strip-actions"><div class="badge success"><i></i>任务运行中</div><button class="binding-settings" data-action="binding-settings">${icon("settings-2")}绑定设置</button></div></section>
      <section class="metrics"><div class="metric"><div class="metric-label">${icon("wallet-cards")}当前资产</div><div class="asset-values"><span class="asset-item"><strong class="asset-number">780</strong><small class="asset-label">积分</small></span><span class="asset-divider"></span><span class="asset-item"><strong class="asset-number">12</strong><small class="asset-label">签到卡</small></span><span class="asset-divider"></span><span class="asset-item"><strong class="asset-number">18</strong><small class="asset-label">能量体</small></span></div><div class="metric-foot">最近查询 08:20</div></div><div class="metric"><div class="metric-label">${icon("flame")}连续签到</div><div class="metric-number">16 <small>天</small></div><div class="metric-foot">连续任务天数</div></div></section>
      <div class="two-columns"><section class="section today-section"><div class="section-header"><div><h2>今日任务</h2><p class="eyebrow">2026 年 09 月 21 日</p></div>${badge("已完成", "success")}</div><div class="task-line"><div class="task-symbol">${icon("calendar-check-2")}</div><div><strong>每日签到</strong><small>今日已完成，重复触发会自动跳过</small></div><span class="task-reward">+6 积分</span>${icon("check")}</div><div class="task-line"><div class="task-symbol energy">${icon("share-2")}</div><div><strong>每日分享</strong><small>签到时同时完成分享</small></div><span class="task-reward energy-text">+2 能量体</span>${icon("check")}</div><div class="next-run">${icon("clock-3")}下一次执行：明天 08:00 - 10:00 内随机执行</div></section><section class="section"><div class="section-header"><div><h2>任务设置</h2><p class="eyebrow">保存后从下一次任务开始生效</p></div>${badge("名额充足", "blue")}</div><form class="schedule-form" data-form="schedule"><label class="field"><span class="field-heading">每日执行区间（北京时间）<span>每两小时随机执行</span></span><select name="window"><option>08:00 - 10:00</option><option>10:00 - 12:00</option><option>12:00 - 14:00</option><option>18:00 - 20:00</option></select></label><div class="availability">本区间剩余 9 / 10 个名额 <span class="availability-bar"><b style="width:90%"></b></span></div><label class="switch-line"><span>签到时同时完成分享</span><input name="share" type="checkbox" ${state.share ? "checked" : ""}></label><div class="form-footer"><span>暂停账号仍占用执行名额</span><div class="form-actions"><button type="button" class="primary" data-action="run">${icon("play")}立即签到一次</button><button type="button" class="pause-task" data-action="pause">${icon("pause")}暂停任务</button><button class="primary" type="submit">${icon("save")}保存设置</button></div></div></form></section></div>
      <section class="push-section"><div><h2>结果推送</h2><p>每次任务完成后发送一次结果通知</p></div><div><div class="push-options"><label>${icon("bell-off")}<input type="radio" name="preview-push" value="none" ${state.push === "none" ? "checked" : ""}>不推送</label><label>${icon("smartphone")}<input type="radio" name="preview-push" value="bark" ${state.push === "bark" ? "checked" : ""}>Bark</label><label>${icon("message-square-text")}<input type="radio" name="preview-push" value="serverchan" ${state.push === "serverchan" ? "checked" : ""}>Server 酱</label></div><div id="push-field" class="push-field" ${state.push === "none" ? "hidden" : ""}><input type="password" placeholder="${state.push === "bark" ? "输入 Bark Device Key" : "输入 Server 酱 SendKey"}"><button data-action="save-push" class="primary">保存并发送测试消息</button></div>${state.pushTestSent ? `<p class="push-test-status">${icon("check-circle-2")}测试消息已发送 · 刚刚</p>` : ""}</div></section>
      <section class="section"><div class="section-header"><div><h2>最近运行</h2><p class="eyebrow">展示最近 7 次云端任务结果</p></div><a class="text-button" href="#history" data-nav="history">查看全部 ${icon("arrow-right")}</a></div><div class="table-wrap"><table><thead><tr><th>执行时间</th><th>任务</th><th>结果</th><th>签到 / 分享</th><th>奖励</th></tr></thead><tbody>${runs.slice(0, 4).map((run) => `<tr><td><strong>${run.date}</strong><small>北京时间</small></td><td>${run.task}</td><td>${badge(run.result, run.tone)}</td><td>${run.sign} / ${run.share}</td><td>${rewardList(run.rewards)}</td></tr>`).join("")}</tbody></table></div></section>`;
  }
  function renderBinding() {
    const steps = ["开始绑定", "配置手机", "验证登录态", "保存到云端", "完成"]; const step = state.bindingStep;
    let panel = "";
    if (step === 0) panel = `<div class="section-kicker">STEP 01 / 05</div><h2>绑定你的账号</h2><p class="subtitle">用手机里的登录状态连接到云端。整个流程只需要操作一次。</p><div class="device-options"><button class="active">${icon("apple")}iPhone</button><button>${icon("smartphone")}安卓手机</button></div><div class="binding-fields"><label class="field"><span>领取链接</span><input placeholder="粘贴管理员发来的领取链接" value="https://daily-task.example/claim/••••••"></label><p class="note">领取链接只用于绑定助手管理账号，不会上传手机里的其他数据。</p><button class="primary" data-action="next-step">${icon("arrow-right")}开始绑定</button></div>`;
    if (step === 1) panel = `<div class="section-kicker">STEP 02 / 05</div><h2>让手机连接电脑</h2><p class="subtitle">电脑和手机连接同一 Wi-Fi，然后扫描二维码完成配对。</p><div class="pair-visual"><div class="qr-placeholder">${icon("qr-code")}</div><div><strong>扫描二维码配对</strong><p>配对后会显示代理地址。示例页面不连接真实手机。</p></div></div><div class="connection-info"><div><span>电脑网络</span><strong>Wi-Fi · 192.168.1.8</strong></div><div><span>代理端口</span><strong>8888</strong></div></div><div class="binding-bottom"><button data-action="previous-step">${icon("arrow-left")}上一步</button><button class="primary" data-action="next-step">手机已配对 ${icon("arrow-right")}</button></div>`;
    if (step === 2) panel = `<div class="section-kicker">STEP 03 / 05</div><h2>验证手机登录状态</h2><p class="subtitle">打开移动端的“我的”页面，抓到必要信息后会自动标记。</p><div class="permission-list"><div><span>登录态</span><strong class="capture-state"><i></i>已抓到</strong></div><div><span>个人信息</span><strong class="capture-state"><i></i>已抓到</strong></div></div><p class="note">登录态和个人信息已识别，敏感内容不会展示在页面中。</p><div class="binding-bottom"><button data-action="previous-step">${icon("arrow-left")}上一步</button><button class="primary" data-action="next-step">确认并继续 ${icon("arrow-right")}</button></div>`;
    if (step === 3) panel = `<div class="section-kicker">STEP 04 / 05</div><h2>保存到云端</h2><p class="subtitle">确认任务设置，登录态会加密保存，手机和云端可以交替续期。</p><div class="connection-info"><div><span>账号名称</span><strong>山海之间</strong></div><div><span>执行区间</span><strong>08:00 - 10:00 · 剩余 9 / 10</strong></div><div><span>每日分享</span><strong>同时完成</strong></div></div><label class="switch-line"><span>我确认这是自己的账号</span><input type="checkbox" checked></label><div class="binding-bottom"><button data-action="previous-step">${icon("arrow-left")}上一步</button><button class="lime" data-action="next-step">保存到云端 ${icon("cloud-upload")}</button></div>`;
    if (step === 4) panel = `<div class="section-kicker">STEP 05 / 05</div><div class="success-mark">${icon("check")}</div><h2>绑定完成</h2><p class="subtitle">每天的任务会在云端执行。你可以随时在概览里调整区间或立即签到。</p><div class="connection-info"><div><span>云端账号</span><strong>山海之间</strong></div><div><span>下次执行</span><strong>明天 08:00 - 10:00</strong></div></div><div class="binding-bottom"><button class="primary" data-action="go-overview">进入账号概览 ${icon("arrow-right")}</button></div>`;
    content.innerHTML = `<div class="page-heading"><div><h1>绑定账号</h1><p class="subtitle">按步骤完成一次设置，之后由云端自动执行</p></div><span class="preview-tag">${icon("wand-2")}仅为页面预览</span></div><div class="binding-layout"><ol class="stepper">${steps.map((name, index) => `<li class="${index === step ? "active" : index < step ? "done" : ""}"><span class="number">${index < step ? icon("check") : index + 1}</span><div><strong>${name}</strong><small>${["选择手机和领取链接", "扫描二维码并配代理", "读取必要登录接口", "设置每日执行任务", "随时在概览查看状态"][index]}</small></div></li>`).join("")}</ol><div class="binding-content">${panel}</div></div>`;
  }
  function renderHistory() {
    const filtered = state.activeFilter === "全部" ? runs : runs.filter((run) => state.activeFilter === "已完成" ? run.tone === "success" : run.tone === "warn");
    content.innerHTML = `<div class="page-heading"><div><h1>运行记录</h1><p class="subtitle">所有云端签到和分享任务都会保留在这里</p></div><button class="primary" data-action="run">${icon("play")}立即签到一次</button></div><div class="filters"><div class="filter-tabs">${["全部", "已完成", "需要关注"].map((filter) => `<button class="${state.activeFilter === filter ? "active" : ""}" data-filter="${filter}">${filter}${filter === "全部" ? ` <span class="micro">${runs.length}</span>` : ""}</button>`).join("")}</div><label class="search">${icon("search")}<input placeholder="搜索日期或任务" data-search></label></div><div class="history-summary"><span>任务次数<strong>24</strong></span><span>完成率<strong>96%</strong></span><span>获得积分<strong>+144</strong></span><span>分享完成<strong>21 次</strong></span></div><div class="table-wrap"><table><thead><tr><th>执行时间</th><th>任务</th><th>结果</th><th>签到 / 分享</th><th>奖励</th><th></th></tr></thead><tbody>${filtered.map((run) => `<tr><td><strong>${run.date}</strong><small>北京时间</small></td><td>${run.task}</td><td>${badge(run.result, run.tone)}</td><td>${run.sign} / ${run.share}</td><td>${rewardList(run.rewards)}</td><td><button class="table-link" data-action="details" data-date="${run.date}">详情 ${icon("chevron-right")}</button></td></tr>`).join("")}</tbody></table>${filtered.length === 0 ? `<div class="empty">${icon("search-x")}没有匹配的记录</div>` : ""}</div><div class="table-footer"><span>显示 ${filtered.length} 条记录 · 示例数据</span><div class="page-controls"><button disabled>${icon("chevron-left")}</button><button class="active">1</button><button>2</button><button>${icon("chevron-right")}</button></div></div>`;
  }
  function renderAdmin() {
    const remaining = 50 - state.batchClaimed;
    content.innerHTML = `<div class="page-heading"><div><h1>管理后台</h1><p class="subtitle">管理领取批次、用户和任务运行情况</p></div><button class="lime" data-action="new-batch">${icon("plus")}生成领取批次</button></div><section class="metrics admin-metrics"><div class="metric"><div class="metric-label">${icon("users")}已领取用户</div><div class="metric-number">${state.claimed}</div><div class="metric-foot">较昨日 <b>+4</b></div></div><div class="metric"><div class="metric-label">${icon("ticket")}可用领取码</div><div class="metric-number">${remaining}</div><div class="metric-foot">批次 20260921-A</div></div><div class="metric"><div class="metric-label">${icon("activity")}今日任务</div><div class="metric-number">31</div><div class="metric-foot"><b>96.8%</b> 成功率</div></div><div class="metric"><div class="metric-label">${icon("bell-ring")}异常提醒</div><div class="metric-number">1</div><div class="metric-foot">等待处理</div></div></section><section class="quota-section"><div class="section-header"><div><h2>两小时区间名额</h2><p class="eyebrow">默认每个区间最多 10 个账号，暂停账号仍保留名额</p></div><div class="legend"><span><i></i>可用</span><span><i class="full"></i>已占用</span></div></div><div class="schedule-bars">${["00-02","02-04","04-06","06-08","08-10","10-12","12-14","14-16","16-18","18-20","20-22","22-24"].map((hour, index) => { const used = index === 4 ? 9 : index === 2 ? 10 : index === 7 ? 6 : index === 9 ? 4 : 2; return `<div class="schedule-column"><div class="bar-track"><div class="bar ${used === 10 ? "full" : ""}" style="height:${used * 10}%"></div></div><strong>${used}/10</strong><small>${hour}</small></div>`; }).join("")}</div></section><section class="section"><div class="section-header"><div><h2>领取批次</h2><p class="eyebrow">用户通过一次性链接自助领取管理空间</p></div></div><div class="table-wrap"><table><thead><tr><th>批次</th><th>领取进度</th><th>有效期</th><th>状态</th><th></th></tr></thead><tbody><tr><td><strong>20260921-A</strong><small>创建于 09/21 09:20</small></td><td>${state.batchClaimed} / 50</td><td>2026/10/21</td><td>${badge("领取中", "success")}</td><td><button class="table-link" data-action="batch">查看链接 ${icon("chevron-right")}</button></td></tr><tr><td><strong>20260918-B</strong><small>创建于 09/18 14:05</small></td><td>100 / 100</td><td>2026/10/18</td><td>${badge("已领完", "blue")}</td><td><button class="table-link" data-action="batch">查看链接 ${icon("chevron-right")}</button></td></tr></tbody></table></div></section>`;
  }
  function render() {
    const allowedViews = ["overview", "binding", "history"];
    const view = allowedViews.includes(state.view) ? state.view : "overview";
    document.querySelectorAll("[data-nav]").forEach((item) => item.classList.toggle("active", item.dataset.nav === view));
    const breadcrumb = document.querySelector("#breadcrumb");
    if (breadcrumb) breadcrumb.textContent = navNames[view];
    if (view === "overview") renderOverview(); else if (view === "binding") renderBinding(); else renderHistory();
    window.lucide?.createIcons();
  }
  function openDialog(kind) {
    if (kind === "recovery") dialogContent.innerHTML = `<div class="dialog-header"><h2>恢复管理权限</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭">${icon("x")}</button></div><div class="dialog-body"><p class="subtitle">恢复码用于更换电脑时重新连接助手管理账号，不是登录凭证。</p><label class="field"><span>恢复码</span><input placeholder="输入 8 位恢复码"></label><div class="preview-callout">示例：恢复成功后，云端已有的任务设置和运行记录会继续保留。</div></div><div class="dialog-footer"><button data-action="close-dialog">取消</button><button class="primary" data-action="recover">恢复连接</button></div>`;
    if (kind === "batch") dialogContent.innerHTML = `<div class="dialog-header"><h2>批次 20260921-A</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭">${icon("x")}</button></div><div class="dialog-body"><div class="detail-row"><span>领取进度</span><strong>${state.batchClaimed} / 50</strong></div><div class="detail-row"><span>有效期</span><strong>2026/10/21 23:59</strong></div><label class="field"><span>领取链接</span><span class="code-value">https://daily-task.example/claim/20260921••••</span></label><div class="preview-callout">链接只显示一次完整内容。实际管理后台支持复制链接和撤销批次。</div></div><div class="dialog-footer"><button data-action="close-dialog">关闭</button><button class="primary" data-action="copy">复制链接</button></div>`;
    if (kind === "new-batch") dialogContent.innerHTML = `<div class="dialog-header"><h2>生成领取批次</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭">${icon("x")}</button></div><div class="dialog-body"><label class="field"><span>领取名额</span><input value="50" type="number" min="1" max="10000"></label><label class="field"><span>有效期</span><select><option>30 天</option><option>7 天</option><option>90 天</option></select></label><div class="preview-callout">生成后会得到一个一次性领取链接。用户打开链接并粘贴到客户端即可完成绑定。</div></div><div class="dialog-footer"><button data-action="close-dialog">取消</button><button class="lime" data-action="create-batch">生成链接</button></div>`;
    if (kind === "unbind") dialogContent.innerHTML = `<div class="dialog-header"><h2>解除账号绑定</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭">${icon("x")}</button></div><div class="dialog-body"><p class="subtitle">这会停止每日任务并删除云端保存的登录状态，助手管理权限会保留。</p><div class="preview-callout">当前为页面预览，点击确认只会展示结果，不会删除任何真实账号数据。</div></div><div class="dialog-footer"><button data-action="close-dialog">取消</button><button class="danger" data-action="confirm-unbind">确认解除绑定</button></div>`;
    if (kind === "binding-settings") dialogContent.innerHTML = `<div class="dialog-header"><h2>绑定设置</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭">${icon("x")}</button></div><div class="dialog-body"><p class="subtitle">管理当前账号与手机登录态的连接。</p><div class="binding-actions"><button class="primary" data-action="replace-binding">${icon("refresh-cw")}更换绑定</button><button class="danger" data-action="unbind">${icon("unlink")}解除绑定</button></div></div><div class="dialog-footer"><button data-action="close-dialog">关闭</button></div>`;
    dialog.showModal(); window.lucide?.createIcons();
  }
  document.addEventListener("click", (event) => {
    const nav = event.target.closest("[data-nav]"); if (nav) { event.preventDefault(); state.view = nav.dataset.nav; history.replaceState(null, "", `#${state.view}`); render(); return; }
    const filter = event.target.closest("[data-filter]"); if (filter) { state.activeFilter = filter.dataset.filter; render(); return; }
    const action = event.target.closest("[data-action]")?.dataset.action; if (!action) return;
    if (action === "run") { notify("已加入立即执行队列，示例页面不会访问实际接口"); return; }
    if (action === "pause") { notify("示例：任务已暂停，再次点击可恢复"); return; }
    if (action === "unbind") { openDialog("unbind"); return; }
    if (action === "binding-settings") { openDialog("binding-settings"); return; }
    if (action === "replace-binding") { dialog.close(); state.bindingStep = 0; state.view = "binding"; history.replaceState(null, "", "#binding"); render(); return; }
    if (action === "next-step") { state.bindingStep = Math.min(4, state.bindingStep + 1); render(); return; }
    if (action === "previous-step") { state.bindingStep = Math.max(0, state.bindingStep - 1); render(); return; }
    if (action === "go-overview") { state.view = "overview"; history.replaceState(null, "", "#overview"); render(); notify("已返回账号概览"); return; }
    if (action === "save-push") { if (state.push === "none") { notify("请先选择一个推送渠道"); return; } state.pushTestSent = true; render(); notify("推送设置已保存，测试消息已发送（示例）"); return; }
    if (action === "recovery" || action === "batch" || action === "new-batch") { openDialog(action); return; }
    if (action === "close-dialog") { dialog.close(); return; }
    if (action === "confirm-unbind") { dialog.close(); notify("已解除绑定（示例）"); return; }
    if (action === "recover") { dialog.close(); notify("恢复连接成功（示例）"); return; }
    if (action === "copy") { notify("领取链接已复制（示例）"); return; }
    if (action === "create-batch") { dialog.close(); state.batchClaimed = 0; notify("已生成新领取批次（示例）"); render(); return; }
    if (action === "reset") { Object.assign(state, initial); history.replaceState(null, "", "#overview"); render(); notify("预览数据已重置"); }
  });
  document.addEventListener("change", (event) => {
    if (event.target.matches('input[name="preview-push"]')) { state.push = event.target.value; render(); }
    if (event.target.matches('input[name="share"]')) state.share = event.target.checked;
  });
  document.addEventListener("submit", (event) => {
    if (event.target.matches('[data-form="schedule"]')) { event.preventDefault(); state.share = event.target.share.checked; notify("每日任务设置已保存（示例）"); }
  });
  window.addEventListener("hashchange", () => { state.view = location.hash.slice(1) || "overview"; render(); });
  render();
})();
